### PR TITLE
This PR adds some code

### PR DESCRIPTION
**Pull request by tkononow**

### CODE REVIEW

**Comment by tkononow** [comment]
@SophieHerbst, @massich, @agramfort This is ready to review.

**Comment by SophieHerbst** [comment]
This is how it renders 0f0a8b6 commit https://6-180820323-gh.circle-artifacts.com/0/doc/index.html

**Comment by SophieHerbst** [comment]
And the last commit failed. @tkononow can you fix it?

**Comment by tkononow** [comment]
conda installation in Circle failed. I trigger it again.

**Comment by massich** [comment]
Cool this is how the website looks like https://8-180820323-gh.circle-artifacts.com/0/doc/index.html

I'll go ahead and merge it. So that the website content is fully `mne-phase` not part of the template, and I'll open some issues with things that should had gone in this PR. So that @tkononow can address them.

**Comment by agramfort** [comment]
great job @tkononow !

**Pull request merged**
